/** Vanilla runtime injected into every generated app. No template literals (safe to embed). */
export const RUNTIME_JS = [
  "(function (global) {",
  "'use strict';",
  "var NF = global.NF || {};",
  "function esc(v) {",
  "  return String(v == null ? '' : v)",
  "    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')",
  "    .replace(/\\\"/g, '&quot;').replace(/'/g, '&#39;');",
  "}",
  "function uid() { return 'e' + Date.now().toString(36) + Math.random().toString(36).slice(2, 7); }",
  "function today() { return new Date().toISOString().slice(0, 10); }",
  "function monthKey(d) { return String(d || '').slice(0, 7); }",
  "function pad(n) { return (n < 10 ? '0' : '') + n; }",
  "function formatDate(d) {",
  "  if (!d) return '—';",
  "  var p = String(d).split('-');",
  "  if (p.length === 3) return p[2] + '/' + p[1] + '/' + p[0];",
  "  return String(d);",
  "}",
  "function money(n) {",
  "  var x = Number(n); if (!isFinite(x)) x = 0;",
  "  try { return x.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' }); }",
  "  catch (e) { return 'R$ ' + x.toFixed(2); }",
  "}",
  "function evalExpr(expr, ctx) {",
  "  if (!expr || !/^[0-9A-Za-z_+\\-*/().\\s]+$/.test(expr)) return 0;",
  "  var keys = Object.keys(ctx);",
  "  var values = keys.map(function (k) { var n = Number(ctx[k]); return isFinite(n) ? n : 0; });",
  "  try {",
  "    var fn = Function.apply(null, keys.concat(['\"use strict\"; return (' + expr + ');']));",
  "    var r = fn.apply(null, values);",
  "    return typeof r === 'number' && isFinite(r) ? Math.round(r * 100) / 100 : 0;",
  "  } catch (e) { return 0; }",
  "}",
  "function prefix() {",
  "  return global.__NF_STORAGE_PREFIX || ('nf_' + ((global.NF_APP && global.NF_APP.slug) || 'app') + '_');",
  "}",
  "function loadDB() {",
  "  try {",
  "    var raw = localStorage.getItem(prefix() + 'db');",
  "    if (raw) return JSON.parse(raw);",
  "  } catch (e) {}",
  "  var db = {};",
  "  var ents = (global.NF_APP && global.NF_APP.entities) || [];",
  "  for (var i = 0; i < ents.length; i++) db[ents[i].key] = [];",
  "  return db;",
  "}",
  "function saveDB(db) {",
  "  try { localStorage.setItem(prefix() + 'db', JSON.stringify(db)); } catch (e) { toast('Sem espaço para salvar'); }",
  "}",
  "var Store = {",
  "  db: {},",
  "  all: function (ent) { return (this.db[ent] || []).slice(); },",
  "  get: function (ent, id) {",
  "    var list = this.db[ent] || [];",
  "    for (var i = 0; i < list.length; i++) if (list[i].id === id) return list[i];",
  "    return null;",
  "  },",
  "  insert: function (ent, row) {",
  "    if (!this.db[ent]) this.db[ent] = [];",
  "    row.id = row.id || uid();",
  "    row.createdAt = row.createdAt || new Date().toISOString();",
  "    this.db[ent].unshift(row);",
  "    saveDB(this.db);",
  "    return row;",
  "  },",
  "  update: function (ent, id, patch) {",
  "    var list = this.db[ent] || [];",
  "    for (var i = 0; i < list.length; i++) {",
  "      if (list[i].id === id) {",
  "        for (var k in patch) if (Object.prototype.hasOwnProperty.call(patch, k)) list[i][k] = patch[k];",
  "        list[i].updatedAt = new Date().toISOString();",
  "        saveDB(this.db);",
  "        return list[i];",
  "      }",
  "    }",
  "    return null;",
  "  },",
  "  remove: function (ent, id) {",
  "    this.db[ent] = (this.db[ent] || []).filter(function (r) { return r.id !== id; });",
  "    saveDB(this.db);",
  "  },",
  "  clear: function () { this.db = loadDBEmpty(); saveDB(this.db); }",
  "};",
  "function loadDBEmpty() {",
  "  var db = {}; var ents = (global.NF_APP && global.NF_APP.entities) || [];",
  "  for (var i = 0; i < ents.length; i++) db[ents[i].key] = [];",
  "  return db;",
  "}",
  "function entitySpec(key) {",
  "  var ents = (global.NF_APP && global.NF_APP.entities) || [];",
  "  for (var i = 0; i < ents.length; i++) if (ents[i].key === key) return ents[i];",
  "  return null;",
  "}",
  "function screenById(id) {",
  "  var ss = (global.NF_APP && global.NF_APP.screens) || [];",
  "  for (var i = 0; i < ss.length; i++) if (ss[i].id === id) return ss[i];",
  "  return ss[0] || { id: 'home', title: 'Início', type: 'dashboard' };",
  "}",
  "function applyCalcs(ent, row) {",
  "  var calcs = (global.NF_APP && global.NF_APP.calculations) || [];",
  "  var ctx = {};",
  "  for (var k in row) if (Object.prototype.hasOwnProperty.call(row, k)) ctx[k] = Number(row[k]);",
  "  if (row.productId) {",
  "    var prod = Store.get('products', row.productId);",
  "    if (prod) {",
  "      if (ctx.unitPrice == null || !isFinite(ctx.unitPrice) || ctx.unitPrice === 0) {",
  "        row.unitPrice = prod.salePrice; ctx.unitPrice = Number(prod.salePrice) || 0;",
  "      }",
  "      if (ctx.costPrice == null || !isFinite(ctx.costPrice)) {",
  "        row.costPrice = prod.costPrice; ctx.costPrice = Number(prod.costPrice) || 0;",
  "      }",
  "    }",
  "  }",
  "  for (var i = 0; i < calcs.length; i++) {",
  "    if (calcs[i].entity === ent) {",
  "      row[calcs[i].field] = evalExpr(calcs[i].expr, ctx);",
  "      ctx[calcs[i].field] = row[calcs[i].field];",
  "    }",
  "  }",
  "  return row;",
  "}",
  "function runHooks(ent, row, isNew) {",
  "  if (!isNew) return;",
  "  var hooks = (global.NF_APP && global.NF_APP.hooks) || [];",
  "  for (var i = 0; i < hooks.length; i++) {",
  "    var h = hooks[i];",
  "    if (h.entity !== ent) continue;",
  "    var matchId = row[h.matchField];",
  "    var target = Store.get(h.targetEntity, matchId);",
  "    if (!target) continue;",
  "    var by = Number(row[h.byField]) || 0;",
  "    var cur = Number(target[h.targetField]) || 0;",
  "    var next = h.action === 'decrement' ? cur - by : cur + by;",
  "    var patch = {}; patch[h.targetField] = next;",
  "    Store.update(h.targetEntity, target.id, patch);",
  "  }",
  "  if (typeof global.NF_HOOKS === 'object' && typeof global.NF_HOOKS.afterSave === 'function') {",
  "    try { global.NF_HOOKS.afterSave({ entity: ent, row: row, store: Store }); } catch (e) {}",
  "  }",
  "}",
  "var route = { screen: 'home', entity: '', id: '', q: '' };",
  "function parseHash() {",
  "  var h = (location.hash || '#/home').replace(/^#\\/?/, '');",
  "  var parts = h.split('/').filter(Boolean);",
  "  route.screen = parts[0] || 'home';",
  "  route.entity = parts[1] || '';",
  "  route.id = parts[2] || '';",
  "}",
  "function go() {",
  "  var args = Array.prototype.slice.call(arguments);",
  "  location.hash = '#/' + args.filter(Boolean).join('/');",
  "}",
  "function toast(msg) {",
  "  var el = document.getElementById('nf-toast');",
  "  if (!el) {",
  "    el = document.createElement('div');",
  "    el.id = 'nf-toast';",
  "    el.className = 'toast';",
  "    document.body.appendChild(el);",
  "  }",
  "  el.textContent = msg;",
  "  el.classList.add('show');",
  "  setTimeout(function () { el.classList.remove('show'); }, 1800);",
  "}",
  "function icon(name) {",
  "  var map = {",
  "    home: 'M4 10.5 12 4l8 6.5V20a1 1 0 0 1-1 1h-5v-6H10v6H5a1 1 0 0 1-1-1z',",
  "    box: 'M3 7.5 12 3l9 4.5v9L12 21l-9-4.5z M3 7.5 12 12l9-4.5 M12 12v9',",
  "    receipt: 'M6 3h12v18l-2-1-2 1-2-1-2 1-2-1-2 1z M8 8h8 M8 12h8 M8 16h5',",
  "    chart: 'M4 19h16 M7 16v-5 M12 16V8 M17 16v-8',",
  "    settings: 'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8z M4 12h2 M18 12h2 M12 4v2 M12 18v2',",
  "    users: 'M9 11a3 3 0 1 0 0-6 3 3 0 0 0 0 6z M5 20v-1a4 4 0 0 1 4-4h0a4 4 0 0 1 4 4v1 M16 11a3 3 0 1 0 0-2 M19 20v-1a3.5 3.5 0 0 0-2-3.2',",
  "    wallet: 'M4 7h16v12H4z M4 7V5h16 M16 13h4',",
  "    check: 'M5 13l4 4L19 7',",
  "    calendar: 'M4 6h16v14H4z M4 10h16 M8 4v4 M16 4v4',",
  "    truck: 'M3 7h11v10H3z M14 11h5l2 3v3h-7z M7 20a2 2 0 1 0 0-4 2 2 0 0 0 0 4z M18 20a2 2 0 1 0 0-4 2 2 0 0 0 0 4z',",
  "    file: 'M7 3h7l5 5v13H7z M14 3v5h5',",
  "    grid: 'M4 4h7v7H4z M13 4h7v7h-7z M4 13h7v7H4z M13 13h7v7h-7z',",
  "    hash: 'M8 4l-2 16 M18 4l-2 16 M4 9h16 M3 15h16',",
  "    list: 'M8 7h12 M8 12h12 M8 17h12 M4 7h.01 M4 12h.01 M4 17h.01',",
  "    repeat: 'M5 8h10l-2-2 M19 16H9l2 2',",
  "    target: 'M12 4v2 M12 18v2 M4 12h2 M18 12h2 M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8z',",
  "    lock: 'M8 10V8a4 4 0 1 1 8 0v2 M6 10h12v10H6z',",
  "    plus: 'M12 5v14 M5 12h14',",
  "    back: 'M15 6l-6 6 6 6',",
  "    search: 'M11 11a5 5 0 1 0 0-10 5 5 0 0 0 0 10z M16 16l-3-3',",
  "    trash: 'M5 7h14 M9 7V5h6v2 M7 7l1 13h8l1-13'",
  "  };",
  "  var d = map[name] || map.file;",
  "  return '<svg class=\"ico\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"' + d + '\"/></svg>';",
  "}",
  "function header(title, opts) {",
  "  opts = opts || {};",
  "  var left = opts.back",
  "    ? '<button class=\"icon-btn\" data-act=\"back\" aria-label=\"Voltar\">' + icon('back') + '</button>'",
  "    : '<div class=\"brand-dot\"></div>';",
  "  var right = opts.add",
  "    ? '<button class=\"icon-btn\" data-act=\"nav\" data-to=\"form/' + esc(opts.add) + '\" aria-label=\"Adicionar\">' + icon('plus') + '</button>'",
  "    : '<span></span>';",
  "  return '<header class=\"top\">' + left + '<h1>' + esc(title) + '</h1>' + right + '</header>';",
  "}",
  "function navBar() {",
  "  var screens = ((global.NF_APP && global.NF_APP.screens) || []).filter(function (s) { return s.nav; }).slice(0, 5);",
  "  var html = '<nav class=\"tabbar\">';",
  "  for (var i = 0; i < screens.length; i++) {",
  "    var s = screens[i];",
  "    var on = route.screen === s.id || (s.entity && route.entity === s.entity && route.screen === 'list');",
  "    if (s.type === 'list' && route.screen === s.id) on = true;",
  "    html += '<button class=\"tab' + (on ? ' on' : '') + '\" data-act=\"nav\" data-to=\"' + esc(s.id) + '\">' + icon(s.icon || 'file') + '<span>' + esc(s.title) + '</span></button>';",
  "  }",
  "  return html + '</nav>';",
  "}",
  "function fieldValue(row, f) {",
  "  if (!row) return '';",
  "  var v = row[f.key];",
  "  if (v == null) return '';",
  "  if (f.type === 'money') return money(v);",
  "  if (f.type === 'date') return formatDate(v);",
  "  if (f.type === 'bool') return v ? 'Sim' : 'Não';",
  "  if (f.type === 'ref' && f.refEntity) {",
  "    var t = Store.get(f.refEntity, v);",
  "    if (t) return t[f.refLabel || 'name'] || v;",
  "  }",
  "  return String(v);",
  "}",
  "function displayTitle(ent, row) {",
  "  if (!row) return '';",
  "  return row.name || row.title || row.customer || row.expr || fieldValue(row, (ent.fields || [])[0] || { key: 'id', type: 'text' }) || row.id;",
  "}",
  "function kpiValue(w) {",
  "  var rows = Store.all(w.entity);",
  "  var nowM = monthKey(today());",
  "  if (w.hint) {",
  "    rows = rows.filter(function (r) {",
  "      var kind = String(r.kind || r.status || '');",
  "      if (w.hint === 'Receita') return kind === 'Receita' || Number(r.amount) > 0 && kind !== 'Despesa';",
  "      if (w.hint === 'Despesa') return kind === 'Despesa';",
  "      return true;",
  "    });",
  "  }",
  "  if (w.op === 'count') {",
  "    if (w.entity === 'tasks') return rows.filter(function (r) { return !r.done; }).length;",
  "    return rows.length;",
  "  }",
  "  var sum = 0;",
  "  for (var i = 0; i < rows.length; i++) {",
  "    if ((w.op === 'monthSum' || w.op === 'profit') && monthKey(rows[i].date) !== nowM) continue;",
  "    if (w.op === 'profit') sum += Number(rows[i][w.field || 'profit']) || 0;",
  "    else sum += Number(rows[i][w.field || 'amount']) || 0;",
  "  }",
  "  if (w.op === 'count') return sum;",
  "  return money(sum);",
  "}",
  "function renderDashboard(screen) {",
  "  var app = global.NF_APP;",
  "  var html = header(app.name) + '<main class=\"page\">';",
  "  html += '<p class=\"lede\">' + esc(app.description || 'Tudo o que você precisa, neste aparelho.') + '</p>';",
  "  html += '<section class=\"kpis\">';",
  "  var widgets = screen.widgets || [];",
  "  for (var i = 0; i < widgets.length; i++) {",
  "    var w = widgets[i];",
  "    html += '<article class=\"kpi\"><span class=\"kpi-label\">' + esc(w.label) + '</span><strong class=\"kpi-val\">' + esc(String(kpiValue(w))) + '</strong></article>';",
  "  }",
  "  html += '</section>';",
  "  var navs = (app.screens || []).filter(function (s) { return s.nav && s.id !== 'home' && s.type !== 'settings' && s.type !== 'login'; });",
  "  html += '<section class=\"actions\">';",
  "  for (var j = 0; j < navs.length; j++) {",
  "    var n = navs[j];",
  "    var addTo = n.entity ? 'form/' + n.entity : n.id;",
  "    html += '<button class=\"card-btn\" data-act=\"nav\" data-to=\"' + esc(n.id) + '\">' + icon(n.icon || 'file') + '<span>' + esc(n.title) + '</span></button>';",
  "    if (n.entity) html += '<button class=\"card-btn ghost\" data-act=\"nav\" data-to=\"' + esc(addTo) + '\">' + icon('plus') + '<span>Novo</span></button>';",
  "  }",
  "  html += '</section>';",
  "  var firstEnt = (app.entities || [])[0];",
  "  if (firstEnt) {",
  "    var recent = Store.all(firstEnt.key).slice(0, 5);",
  "    html += '<h2 class=\"h2\">Recentes</h2>';",
  "    if (!recent.length) html += '<p class=\"empty\">Nada por aqui ainda. Toque em Novo para começar.</p>';",
  "    html += '<ul class=\"rows\">';",
  "    for (var r = 0; r < recent.length; r++) {",
  "      var row = recent[r];",
  "      html += '<li><button class=\"row\" data-act=\"nav\" data-to=\"detail/' + esc(firstEnt.key) + '/' + esc(row.id) + '\"><span>' + esc(displayTitle(firstEnt, row)) + '</span><em>' + esc(fieldValue(row, firstEnt.fields[1] || firstEnt.fields[0])) + '</em></button></li>';",
  "    }",
  "    html += '</ul>';",
  "  }",
  "  return html + '</main>' + navBar();",
  "}",
  "function renderList(screen) {",
  "  var key = screen.entity || route.entity;",
  "  var ent = entitySpec(key);",
  "  if (!ent) return header('Lista') + '<main class=\"page\"><p>Nada para listar.</p></main>' + navBar();",
  "  var q = (document.getElementById('nf-q') && document.getElementById('nf-q').value) || route.q || '';",
  "  var rows = Store.all(ent.key);",
  "  var keys = ent.search || [];",
  "  if (q) {",
  "    var qq = q.toLowerCase();",
  "    rows = rows.filter(function (row) {",
  "      for (var i = 0; i < keys.length; i++) {",
  "        if (String(row[keys[i]] || '').toLowerCase().indexOf(qq) !== -1) return true;",
  "      }",
  "      return String(displayTitle(ent, row)).toLowerCase().indexOf(qq) !== -1;",
  "    });",
  "  }",
  "  if (ent.sortKey) {",
  "    var dir = ent.sortDir === 'asc' ? 1 : -1;",
  "    var sk = ent.sortKey;",
  "    rows.sort(function (a, b) { return a[sk] < b[sk] ? -1 * dir : a[sk] > b[sk] ? 1 * dir : 0; });",
  "  }",
  "  var html = header(ent.plural, { add: ent.key }) + '<main class=\"page\">';",
  "  html += '<div class=\"search\"><span>' + icon('search') + '</span><input id=\"nf-q\" placeholder=\"Buscar\" value=\"' + esc(q) + '\" data-act=\"search\" data-entity=\"' + esc(ent.key) + '\"></div>';",
  "  if (!rows.length) html += '<p class=\"empty\">Nenhum registro. Toque em + para adicionar.</p>';",
  "  html += '<ul class=\"rows\">';",
  "  for (var i = 0; i < rows.length; i++) {",
  "    var row = rows[i];",
  "    var sub = ent.fields[1] ? fieldValue(row, ent.fields[1]) : '';",
  "    html += '<li><button class=\"row\" data-act=\"nav\" data-to=\"detail/' + esc(ent.key) + '/' + esc(row.id) + '\"><span>' + esc(displayTitle(ent, row)) + '</span><em>' + esc(sub) + '</em></button></li>';",
  "  }",
  "  return html + '</ul></main>' + navBar();",
  "}",
  "function inputFor(f, value) {",
  "  var req = f.required ? ' required' : '';",
  "  var val = value == null ? '' : value;",
  "  if (f.type === 'textarea') return '<textarea name=\"' + esc(f.key) + '\" rows=\"4\"' + req + '>' + esc(val) + '</textarea>';",
  "  if (f.type === 'bool') return '<label class=\"chk\"><input type=\"checkbox\" name=\"' + esc(f.key) + '\"' + (val ? ' checked' : '') + '> Sim</label>';",
  "  if (f.type === 'select') {",
  "    var html = '<select name=\"' + esc(f.key) + '\"' + req + '>';",
  "    var opts = f.options || [];",
  "    html += '<option value=\"\"></option>';",
  "    for (var i = 0; i < opts.length; i++) html += '<option' + (String(val) === opts[i] ? ' selected' : '') + '>' + esc(opts[i]) + '</option>';",
  "    return html + '</select>';",
  "  }",
  "  if (f.type === 'ref') {",
  "    var list = Store.all(f.refEntity || '');",
  "    var html2 = '<select name=\"' + esc(f.key) + '\"' + req + '><option value=\"\"></option>';",
  "    for (var j = 0; j < list.length; j++) {",
  "      var lab = list[j][f.refLabel || 'name'] || list[j].id;",
  "      html2 += '<option value=\"' + esc(list[j].id) + '\"' + (val === list[j].id ? ' selected' : '') + '>' + esc(lab) + '</option>';",
  "    }",
  "    return html2 + '</select>';",
  "  }",
  "  var t = 'text';",
  "  if (f.type === 'number' || f.type === 'money') t = 'number';",
  "  if (f.type === 'date') t = 'date';",
  "  if (f.type === 'time') t = 'time';",
  "  if (f.type === 'email') t = 'email';",
  "  if (f.type === 'tel') t = 'tel';",
  "  var extra = '';",
  "  if (f.min != null) extra += ' min=\"' + f.min + '\"';",
  "  if (f.max != null) extra += ' max=\"' + f.max + '\"';",
  "  if (f.step != null) extra += ' step=\"' + f.step + '\"';",
  "  if (f.type === 'money') extra += ' step=\"0.01\"';",
  "  return '<input type=\"' + t + '\" name=\"' + esc(f.key) + '\" value=\"' + esc(val) + '\"' + req + extra + '>';",
  "}",
  "function renderForm(screen) {",
  "  var key = screen.entity || route.entity || route.screen;",
  "  var ent = entitySpec(key);",
  "  if (!ent) return header('Formulário') + '<main class=\"page\"><p>Formulário indisponível.</p></main>' + navBar();",
  "  var row = route.id ? Store.get(ent.key, route.id) : null;",
  "  var html = header(row ? 'Editar' : 'Novo ' + ent.label, { back: true }) + '<main class=\"page\">';",
  "  html += '<form id=\"nf-form\" data-act=\"save\" data-entity=\"' + esc(ent.key) + '\" data-id=\"' + esc(row ? row.id : '') + '\">';",
  "  for (var i = 0; i < ent.fields.length; i++) {",
  "    var f = ent.fields[i];",
  "    var computed = false;",
  "    var calcs = global.NF_APP.calculations || [];",
  "    for (var c = 0; c < calcs.length; c++) if (calcs[c].entity === ent.key && calcs[c].field === f.key) computed = true;",
  "    html += '<label class=\"fld\"><span>' + esc(f.label) + (f.required ? ' *' : '') + (computed ? ' (automático)' : '') + '</span>' + inputFor(f, row ? row[f.key] : (f.type === 'date' ? today() : '')) + '</label>';",
  "  }",
  "  html += '<button class=\"btn\" type=\"submit\">Salvar</button></form></main>' + navBar();",
  "  return html;",
  "}",
  "function renderDetail(screen) {",
  "  var key = route.entity || screen.entity;",
  "  var ent = entitySpec(key);",
  "  var row = ent ? Store.get(ent.key, route.id) : null;",
  "  if (!ent || !row) return header('Detalhe', { back: true }) + '<main class=\"page\"><p>Registro não encontrado.</p></main>' + navBar();",
  "  var html = header(displayTitle(ent, row), { back: true }) + '<main class=\"page\"><dl class=\"kv\">';",
  "  for (var i = 0; i < ent.fields.length; i++) {",
  "    var f = ent.fields[i];",
  "    html += '<div><dt>' + esc(f.label) + '</dt><dd>' + esc(fieldValue(row, f)) + '</dd></div>';",
  "  }",
  "  html += '</dl><div class=\"split\">';",
  "  html += '<button class=\"btn\" data-act=\"nav\" data-to=\"form/' + esc(ent.key) + '/' + esc(row.id) + '\">Editar</button>';",
  "  html += '<button class=\"btn danger\" data-act=\"delete\" data-entity=\"' + esc(ent.key) + '\" data-id=\"' + esc(row.id) + '\">Excluir</button>';",
  "  html += '</div></main>' + navBar();",
  "  return html;",
  "}",
  "function renderReport() {",
  "  var app = global.NF_APP;",
  "  var html = header('Relatórios') + '<main class=\"page\">';",
  "  var reps = app.reports || [];",
  "  if (!reps.length) html += '<p class=\"empty\">Nenhum relatório configurado.</p>';",
  "  for (var i = 0; i < reps.length; i++) {",
  "    var rp = reps[i];",
  "    var rows = Store.all(rp.entity);",
  "    var groups = {};",
  "    for (var r = 0; r < rows.length; r++) {",
  "      var g = rp.groupBy === 'status' ? (rows[r].status || '—') : rp.groupBy === 'day' ? (rows[r].date || '—') : monthKey(rows[r].date || rows[r].createdAt);",
  "      if (!g) g = '—';",
  "      if (!groups[g]) groups[g] = { n: 0, total: 0, profit: 0 };",
  "      groups[g].n += 1;",
  "      groups[g].total += Number(rows[r].total != null ? rows[r].total : rows[r].amount) || 0;",
  "      groups[g].profit += Number(rows[r].profit) || 0;",
  "    }",
  "    html += '<section class=\"card\"><h2 class=\"h2\">' + esc(rp.title) + '</h2><ul class=\"rows\">';",
  "    var keys = Object.keys(groups).sort().reverse();",
  "    var max = 1;",
  "    for (var m = 0; m < keys.length; m++) if (groups[keys[m]].total > max) max = groups[keys[m]].total;",
  "    for (var k = 0; k < keys.length; k++) {",
  "      var item = groups[keys[k]];",
  "      var pct = Math.round((item.total / max) * 100);",
  "      html += '<li class=\"rep\"><div class=\"rep-h\"><span>' + esc(keys[k]) + '</span><strong>' + esc(money(item.total)) + '</strong></div>';",
  "      html += '<div class=\"bar\"><i style=\"width:' + pct + '%\"></i></div>';",
  "      html += '<p class=\"muted\">' + item.n + ' registro(s)' + (item.profit ? ' · lucro ' + money(item.profit) : '') + '</p></li>';",
  "    }",
  "    if (!keys.length) html += '<li class=\"muted\">Sem dados neste período.</li>';",
  "    html += '</ul></section>';",
  "  }",
  "  return html + '</main>' + navBar();",
  "}",
  "function renderCatalog(screen) {",
  "  var ent = entitySpec(screen.entity || 'items');",
  "  var qel = document.getElementById('nf-q');",
  "  var q = (qel && qel.value) || '';",
  "  var rows = Store.all(ent ? ent.key : 'items');",
  "  if (q) rows = rows.filter(function (r) { return String(r.name || '').toLowerCase().indexOf(q.toLowerCase()) !== -1; });",
  "  var html = header(screen.title) + '<main class=\"page\"><div class=\"search\"><span>' + icon('search') + '</span><input id=\"nf-q\" placeholder=\"Buscar\" value=\"' + esc(q) + '\" data-act=\"search\"></div>';",
  "  html += '<div class=\"grid\">';",
  "  if (!rows.length) html += '<p class=\"empty\">Nenhum item no catálogo.</p>';",
  "  for (var i = 0; i < rows.length; i++) {",
  "    html += '<article class=\"tile\"><h3>' + esc(rows[i].name) + '</h3><p>' + esc(rows[i].desc || rows[i].category || '') + '</p><strong>' + esc(money(rows[i].price)) + '</strong></article>';",
  "  }",
  "  return html + '</div></main>' + navBar();",
  "}",
  "function renderCalendar(screen) {",
  "  var ent = entitySpec(screen.entity || 'events');",
  "  var rows = Store.all(ent ? ent.key : 'events');",
  "  var selected = route.id || today();",
  "  var now = new Date(selected + 'T00:00:00');",
  "  if (isNaN(now.getTime())) now = new Date();",
  "  var y = now.getFullYear(), m = now.getMonth();",
  "  var first = new Date(y, m, 1).getDay();",
  "  var days = new Date(y, m + 1, 0).getDate();",
  "  var html = header(screen.title, { add: ent ? ent.key : 'events' }) + '<main class=\"page\">';",
  "  html += '<div class=\"cal-h\"><button class=\"icon-btn\" data-act=\"nav\" data-to=\"' + screen.id + '/' + y + '-' + pad(m) + '-01\">‹</button><strong>' + esc(now.toLocaleString('pt-BR', { month: 'long', year: 'numeric' })) + '</strong><button class=\"icon-btn\" data-act=\"nav\" data-to=\"' + screen.id + '/' + y + '-' + pad(m + 2) + '-01\">›</button></div>';",
  "  html += '<div class=\"cal\">';",
  "  var names = ['D','S','T','Q','Q','S','S'];",
  "  for (var n = 0; n < 7; n++) html += '<span class=\"dow\">' + names[n] + '</span>';",
  "  for (var b = 0; b < first; b++) html += '<span></span>';",
  "  for (var d = 1; d <= days; d++) {",
  "    var iso = y + '-' + pad(m + 1) + '-' + pad(d);",
  "    var has = rows.some(function (r) { return r.date === iso; });",
  "    html += '<button class=\"day' + (iso === today() ? ' today' : '') + (has ? ' has' : '') + '\" data-act=\"nav\" data-to=\"' + screen.id + '/' + iso + '\">' + d + '</button>';",
  "  }",
  "  html += '</div><h2 class=\"h2\">' + formatDate(selected) + '</h2><ul class=\"rows\">';",
  "  var dayRows = rows.filter(function (r) { return r.date === selected; });",
  "  if (!dayRows.length) html += '<p class=\"empty\">Nenhum compromisso neste dia.</p>';",
  "  for (var i = 0; i < dayRows.length; i++) {",
  "    html += '<li><button class=\"row\" data-act=\"nav\" data-to=\"detail/' + esc(ent.key) + '/' + esc(dayRows[i].id) + '\"><span>' + esc(dayRows[i].title) + '</span><em>' + esc(dayRows[i].time || '') + '</em></button></li>';",
  "  }",
  "  return html + '</ul></main>' + navBar();",
  "}",
  "function streak(habitId) {",
  "  var set = {};",
  "  Store.all('checkins').forEach(function (c) { if (c.habitId === habitId) set[c.date] = true; });",
  "  var n = 0; var d = new Date();",
  "  for (;;) {",
  "    var iso = d.toISOString().slice(0, 10);",
  "    if (!set[iso]) break;",
  "    n += 1;",
  "    d.setDate(d.getDate() - 1);",
  "  }",
  "  return n;",
  "}",
  "function renderHabits() {",
  "  var habits = Store.all('habits');",
  "  var html = header('Hábitos', { add: 'habits' }) + '<main class=\"page\">';",
  "  if (!habits.length) html += '<p class=\"empty\">Crie um hábito e marque cada dia em que cumpri-lo.</p>';",
  "  for (var i = 0; i < habits.length; i++) {",
  "    var h = habits[i];",
  "    var on = Store.all('checkins').some(function (c) { return c.habitId === h.id && c.date === today(); });",
  "    html += '<div class=\"habit\"><div><strong>' + esc(h.name) + '</strong><span class=\"muted\">Sequência: ' + streak(h.id) + ' dia(s)</span></div>';",
  "    html += '<button class=\"chip' + (on ? ' on' : '') + '\" data-act=\"checkin\" data-id=\"' + esc(h.id) + '\">' + (on ? 'Feito' : 'Marcar') + '</button></div>';",
  "  }",
  "  return html + '</main>' + navBar();",
  "}",
  "function renderCalculator() {",
  "  var cur = (global.__nf_calc = global.__nf_calc || { expr: '', value: '0' });",
  "  var keys = ['C','⌫','%','/','7','8','9','*','4','5','6','-','1','2','3','+','0','.','='];",
  "  var html = header('Calculadora') + '<main class=\"page calc-wrap\"><div class=\"calc-screen\"><span>' + esc(cur.expr) + '</span><strong>' + esc(cur.value) + '</strong></div><div class=\"calc-keys\">';",
  "  for (var i = 0; i < keys.length; i++) {",
  "    html += '<button class=\"k' + (keys[i] === '=' ? ' eq' : '') + '\" data-act=\"calc\" data-k=\"' + esc(keys[i]) + '\">' + esc(keys[i]) + '</button>';",
  "  }",
  "  return html + '</div></main>' + navBar();",
  "}",
  "function doCalc(k) {",
  "  var st = (global.__nf_calc = global.__nf_calc || { expr: '', value: '0' });",
  "  if (k === 'C') { st.expr = ''; st.value = '0'; return; }",
  "  if (k === '⌫') { st.value = st.value.slice(0, -1) || '0'; return; }",
  "  if (k === '=') {",
  "    var expr = (st.expr + st.value).replace(/%/g, '/100');",
  "    var r = evalExpr(expr, {});",
  "    st.expr = expr + ' =';",
  "    st.value = String(r);",
  "    if (entitySpec('history')) Store.insert('history', { expr: expr, result: String(r) });",
  "    return;",
  "  }",
  "  if ('+-*/'.indexOf(k) !== -1) { st.expr += st.value + ' ' + k + ' '; st.value = '0'; return; }",
  "  if (st.value === '0' && k !== '.') st.value = k; else st.value += k;",
  "}",
  "function renderSettings() {",
  "  var app = global.NF_APP;",
  "  var html = header('Ajustes') + '<main class=\"page\">';",
  "  html += '<section class=\"card\"><h2 class=\"h2\">' + esc(app.name) + '</h2><p class=\"muted\">' + esc(app.description) + '</p></section>';",
  "  html += '<button class=\"btn\" data-act=\"export\">Exportar dados (JSON)</button>';",
  "  html += '<button class=\"btn ghost\" data-act=\"wipe\">Apagar dados deste app</button>';",
  "  html += '<p class=\"muted tiny\">Os dados ficam neste aparelho. Nada é enviado à internet.</p>';",
  "  return html + '</main>' + navBar();",
  "}",
  "function renderLogin() {",
  "  var html = header('Entrar') + '<main class=\"page\"><form id=\"nf-login\" data-act=\"login\" class=\"card\">';",
  "  html += '<label class=\"fld\"><span>Senha local</span><input type=\"password\" name=\"pin\" required minlength=\"4\"></label>';",
  "  html += '<p class=\"muted\">Defina uma senha na primeira vez. Ela fica só neste aparelho.</p>';",
  "  html += '<button class=\"btn\" type=\"submit\">Continuar</button></form></main>';",
  "  return html;",
  "}",
  "function gated() {",
  "  var hasLogin = ((global.NF_APP && global.NF_APP.screens) || []).some(function (s) { return s.type === 'login'; });",
  "  if (!hasLogin) return false;",
  "  try { return localStorage.getItem(prefix() + 'ok') !== '1'; } catch (e) { return false; }",
  "}",
  "function render() {",
  "  parseHash();",
  "  var root = document.getElementById('app');",
  "  if (!root) return;",
  "  if (gated() && route.screen !== 'login') { root.innerHTML = renderLogin(); bind(); return; }",
  "  var screen = screenById(route.screen);",
  "  var html = '';",
  "  if (route.screen === 'form') html = renderForm(screen);",
  "  else if (route.screen === 'detail') html = renderDetail(screen);",
  "  else if (screen.type === 'dashboard') html = renderDashboard(screen);",
  "  else if (screen.type === 'list') html = renderList(screen);",
  "  else if (screen.type === 'form') html = renderForm(screen);",
  "  else if (screen.type === 'report') html = renderReport();",
  "  else if (screen.type === 'catalog') html = renderCatalog(screen);",
  "  else if (screen.type === 'calendar') html = renderCalendar(screen);",
  "  else if (screen.type === 'habits') html = renderHabits();",
  "  else if (screen.type === 'calculator') html = renderCalculator();",
  "  else if (screen.type === 'settings') html = renderSettings();",
  "  else if (screen.type === 'login') html = renderLogin();",
  "  else html = renderDashboard(screen);",
  "  root.innerHTML = html;",
  "  bind();",
  "}",
  "function readForm(form) {",
  "  var data = {};",
  "  var els = form.elements;",
  "  for (var i = 0; i < els.length; i++) {",
  "    var el = els[i];",
  "    if (!el.name) continue;",
  "    if (el.type === 'checkbox') data[el.name] = !!el.checked;",
  "    else data[el.name] = el.value;",
  "  }",
  "  return data;",
  "}",
  "function bind() {",
  "  var root = document.getElementById('app');",
  "  if (!root) return;",
  "  root.onclick = function (ev) {",
  "    var t = ev.target;",
  "    while (t && t !== root && !(t.getAttribute && t.getAttribute('data-act'))) t = t.parentNode;",
  "    if (!t || t === root) return;",
  "    var act = t.getAttribute('data-act');",
  "    if (act === 'nav') { ev.preventDefault(); go.apply(null, String(t.getAttribute('data-to') || 'home').split('/')); }",
  "    if (act === 'back') { ev.preventDefault(); history.back(); }",
  "    if (act === 'delete') {",
  "      ev.preventDefault();",
  "      if (confirm('Excluir este registro?')) {",
  "        Store.remove(t.getAttribute('data-entity'), t.getAttribute('data-id'));",
  "        toast('Excluído');",
  "        go(t.getAttribute('data-entity'));",
  "      }",
  "    }",
  "    if (act === 'wipe') {",
  "      ev.preventDefault();",
  "      if (confirm('Apagar todos os dados deste aplicativo neste aparelho?')) { Store.db = loadDBEmpty(); saveDB(Store.db); toast('Dados apagados'); render(); }",
  "    }",
  "    if (act === 'export') {",
  "      ev.preventDefault();",
  "      var blob = new Blob([JSON.stringify(Store.db, null, 2)], { type: 'application/json' });",
  "      var a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = (global.NF_APP.slug || 'dados') + '.json'; a.click();",
  "    }",
  "    if (act === 'checkin') {",
  "      ev.preventDefault();",
  "      var hid = t.getAttribute('data-id');",
  "      var existing = Store.all('checkins').filter(function (c) { return c.habitId === hid && c.date === today(); });",
  "      if (existing.length) Store.remove('checkins', existing[0].id);",
  "      else Store.insert('checkins', { habitId: hid, date: today() });",
  "      render();",
  "    }",
  "    if (act === 'calc') { ev.preventDefault(); doCalc(t.getAttribute('data-k')); render(); }",
  "  };",
  "  var form = document.getElementById('nf-form');",
  "  if (form) form.onsubmit = function (ev) {",
  "    ev.preventDefault();",
  "    var entKey = form.getAttribute('data-entity');",
  "    var id = form.getAttribute('data-id');",
  "    var row = applyCalcs(entKey, readForm(form));",
  "    if (id) { Store.update(entKey, id, row); toast('Salvo'); }",
  "    else { Store.insert(entKey, row); runHooks(entKey, row, true); toast('Adicionado'); }",
  "    go(entKey);",
  "  };",
  "  var login = document.getElementById('nf-login');",
  "  if (login) login.onsubmit = function (ev) {",
  "    ev.preventDefault();",
  "    var pin = login.pin.value;",
  "    var saved = null; try { saved = localStorage.getItem(prefix() + 'pin'); } catch (e) {}",
  "    if (!saved) { try { localStorage.setItem(prefix() + 'pin', pin); } catch (e) {} }",
  "    else if (saved !== pin) { toast('Senha incorreta'); return; }",
  "    try { localStorage.setItem(prefix() + 'ok', '1'); } catch (e) {}",
  "    go('home');",
  "  };",
  "  var sq = document.getElementById('nf-q');",
  "  if (sq) sq.oninput = function () { route.q = sq.value; /* live filter */ var screen = screenById(route.screen); if (screen.type === 'list') { var html = renderList(screen); document.getElementById('app').innerHTML = html; bind(); var n = document.getElementById('nf-q'); if (n) { n.focus(); n.value = route.q; n.setSelectionRange(n.value.length, n.value.length); } } };",
  "}",
  "NF.boot = function (app) {",
  "  global.NF_APP = app;",
  "  Store.db = loadDB();",
  "  var ents = app.entities || [];",
  "  for (var i = 0; i < ents.length; i++) if (!Store.db[ents[i].key]) Store.db[ents[i].key] = [];",
  "  document.title = app.name || 'App';",
  "  document.documentElement.setAttribute('data-theme', (app.theme && app.theme.mode) || 'light');",
  "  if (app.theme && app.theme.primary) document.documentElement.style.setProperty('--p', app.theme.primary);",
  "  if (app.theme && app.theme.primaryFg) document.documentElement.style.setProperty('--pfg', app.theme.primaryFg);",
  "  window.addEventListener('hashchange', render);",
  "  render();",
  "};",
  "NF.go = go; NF.store = Store; NF.esc = esc; NF.money = money; NF.evalExpr = evalExpr;",
  "global.NF = NF;",
  "})(typeof window !== 'undefined' ? window : globalThis);",
].join("\n");
