UPSTREAM_REPOSITORY=https://github.com/xororz/local-dream.git
UPSTREAM_TAG=v2.0.0
FILTERED_APK_URL=https://github.com/xororz/local-dream/releases/download/v2.0.0/LocalDream_armv8a_2.0.0_with_filter.apk
FILTERED_APK_SHA256=50e86bcf550913ae8069a22bedb2b065b72e762570509580d524338c8fb5a221

